name: Main workflow

on: [push]

jobs:
  build:
    runs-on: debian-latest
    container: ocaml/opam:debian-10-ocaml-4.06
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - run: opam install dune
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
