name: Main workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ocaml/opam:debian-10-ocaml-4.06
    steps:
      - run: git clone https://github.com/casually-blue/sierra-compiler-ocaml
      - run: cd sierra-compiler-ocaml
        
      - run: opam install dune
      - run: opam exec -- dune build
      - run: opam exec -- dune runtest
